root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
  bin = "./build"
  cmd = "go build -o ./build/main ./main.go"
  delay = 1000
  exclude_dir = ["assets", "build", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  follow_symlink = false
  full_bin = "./build/main"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = false
  delay = 1000 # ms

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
